### ISSUE TITLE
Why is a confidence value of 100 not okay?

### ISSUE THREAD

**Issue by zuphilip** [kba/hocr-spec-python#4]
I see an error for the following part of an hocr file
```html
                  <span class="ocrx_word"
                        id="word_w1aab5b1b1b5b2a"
                        title="bbox 37 82 112 102 ; x_wconf 100">LEVEL</span>
```
because the `x_wconf`-value is 100. Is that not okay?

I would have thought that any value in [0, 100] is fine (including the edge case). For a recognition tool it might be unusual to be absolutely sure, i.e. have 100 % confidence, but especially with some rounding this might happen.

Here is a real life example from the transformed from ALTO and initially used ABBYY Finereader: https://gist.github.com/zuphilip/bcfddac899419e73b48344f6bd9e1446

**Comment by kba** [comment]
That's a bug, range check should include the min/max. I'll update.

**Comment by kba** [comment]
Fixed, please try master or update from PyPI.
